### ISSUE TITLE
[Suggestion] Compatibility with Enchanting Infuser

### ISSUE THREAD

**Issue by WhitePhant0m** [Fourmisain/TaxFreeLevels#12]
Would it be possible to add compatibility with [Enchanting Infuser](https://modrinth.com/mod/enchanting-infuser)(fabric)?
Specifically for version 1.19, if not too hard, then also for 1.19.1

**Comment by Fourmisain** [comment]
Released a new version with support for it (and a bunch of other mods).
I haven't actually tested the 1.19 version but it'll most likely work without any issues.
