### ISSUE TITLE
Server Crash on connecting to Server - Waystones x TaxFreeLevels (1.18.2)

### ISSUE THREAD

**Issue by Lokilotus** [Fourmisain/TaxFreeLevels#13]
Using TFL 1.3.4, Waystones 10.2.0.

Steps to reproduce:
1. Place TFL 1.3.4 and Waystones 10.2.0 on client and server.
2. Start Server; starts as normal and waits patiently for a client to connect.
3. Connect a client to the Server.
4. Server Crashes. Client times out as server has crashed but does not crash to desktop.

Seems to be to do with mixins. Changing the Waystones config to not use XP does not fix the issue.

Server Crashlog here: [crash-2023-03-04_17.01.49-server.txt](https://github.com/Fourmisain/TaxFreeLevels/files/10889224/crash-2023-03-04_17.01.49-server.txt)

Crossposted issue here: https://github.com/TwelveIterationMods/Waystones/issues/675

**Comment by Fourmisain** [comment]
fixed in 1.3.5!
