### ISSUE TITLE
Forge 1.19.4 crash on startup (Mixin apply failed)

### ISSUE THREAD

**Issue by NancalaStarry** [Fourmisain/TaxFreeLevels#18]
Log here: [latest.log](https://github.com/Fourmisain/TaxFreeLevels/files/11928981/latest.log)

**Comment by Fourmisain** [comment]
Balanced Enchanting is incompatible with Tax Free Levels.
You can simply remove it as it does more or less the same as Tax Free Levels minus all the compatibility stuff.
Lemme know if there's still any issue.

**Comment by NancalaStarry** [comment]
yeah so sorry that I made a very stupid mistake
