### ISSUE TITLE
No parity with Grind Enchantments

### ISSUE THREAD

**Issue by Neubulae** [Fourmisain/TaxFreeLevels#2]
https://www.curseforge.com/minecraft/mc-mods/grind-enchantments
I still get non-flattened cost with this.

**Comment by Fourmisain** [comment]
I just tested this, their last version (1.2.0 for 1.17) added support for this mod and it does flatten the cost.
Are you on 1.16 by any chance?

**Comment by Neubulae** [comment]
Oh uh, yeah, I'm on 1.16

**Comment by Fourmisain** [comment]
Just for you I backported the Tax Free Levels support of Grind Enchantments to 1.16.
You can download the release [here](https://github.com/Fourmisain/grind-enchantments/releases/tag/1.1.3-TaxFreeLevels).

**Comment by Neubulae** [comment]
Oh, thanks!
