### ISSUE TITLE
Crash with Enchanting Infuser v.8.0.2 [Fabric 1.20.1]

### ISSUE THREAD

**Issue by mpustovoi** [Fourmisain/TaxFreeLevels#20]
With the latest update of Enchanting Infuser mod the mixin broke.
Featured mods:
• **Enchanting Infuser**-v.8.0.2
• **Tax Free Levels** v.1.3.3
Crash Report:
https://gist.github.com/mpustovoi/5eaa6271f46e3fcaaa573343f61b90ee
latest.log:
https://gist.github.com/mpustovoi/1ebe1697b6f63c26d8174426cf0898df

**Comment by mpustovoi** [comment]
https://github.com/Fuzss/enchantinginfuser/issues/62#issuecomment-1762928224_

**Comment by Fourmisain** [comment]
Ah, that's really bad timing.
My PC refuses to boot and I'm stuck on a laptop without any of my dev stuff.
Hopefully I can get it up and running again tomorrow.

For the time being I uploaded a version without the Enchanting Infuser mixin:
https://github.com/Fourmisain/TaxFreeLevels/releases/download/tempfix/TaxFreeLevels-1.3.3-fabric-1.19-tempfix.jar

**Comment by Fourmisain** [comment]
Aight, managed to fix my PC (it was the PSU) and the mixin crash as well.
New version 1.3.6 should be compatible with old and new Enchanting Infuser versions.
