### ISSUE TITLE
Enchanting Infuser (Forge) compatibility

### ISSUE THREAD

**Issue by GregHilmes** [Fourmisain/TaxFreeLevels#23]
I see Tax Free Levels added compatibility with Enchanting Infuser in f82f35afd34b048e1e4a0c895e47a5bc29d41901, but that support seems to only be with Fabric. When running both mods in Forge, the normal level cost remains.

Setup:
- Minecraft 1.18.2
- Forge 40.2.7
- Tax Free Levels 1.3.8
- Enchanting Infuser 3.3.3
- Puzzels Lib 3.5.8 (Required by Enchanting Infuser)

Would it be possible to replicate the enchanting infuser mixin/compatibility for Forge?

**Comment by Fourmisain** [comment]
Oh, I added support for it before I even ported my mod to Forge and I never looked to check! 😅

1.3.9 with support for it for Forge and NeoForge is now up!

**Comment by GregHilmes** [comment]
Works perfectly, thanks for the quick response!
