### ISSUE TITLE
1.19.2 Apotheosis crash 

### ISSUE THREAD

**Issue by DFreezerR** [Fourmisain/TaxFreeLevels#24]
Hi, apparently MC is crashing when you try to launch it with [TaxFreeLevels](https://github.com/Fourmisain/TaxFreeLevels) + [Apotheosis](https://github.com/Shadows-of-Fire/Apotheosis) the latest release version for MC 1.19.2
I saw there are responses in Issues that there was made a compatibility update with that mod, so I think that just a new bug rather than "complete" incompatibility.

Can fix with downgrading Apotheosis to 6.4.1 version. 

Log - [log.txt](https://github.com/Fourmisain/TaxFreeLevels/files/14972564/log.txt)
Forge              - 43.3.0
Apotheosis     - 6.5.0
TaxFreeLevels - 1.3.9

**Comment by Fourmisain** [comment]
Ah, they backported some stuff from 7.2.0+ but the version is 6.5.0, so the compatibility check doesn't pass:
https://github.com/Fourmisain/TaxFreeLevels/blob/0fcf2a2543ddf6127674a63715aa10a6f4915307/forge/src/main/java/io/github/fourmisain/taxfreelevels/forge/MixinConfig.java#L51-L53

Easy fix, I'll just put 6.5.0.
(Technically breaks support for 7.1.0, but there's no reason to use that over 7.2.0+.)

New version 1.3.10 is up!
