### ISSUE TITLE
Crash with Waystones mod 1.20.1 Forge

### ISSUE THREAD

**Issue by Maisman** [Fourmisain/TaxFreeLevels#25]
1.3.9 does work with Waystones. 
The latest version 1.3.10 crashing.

**Comment by Crafttim** [comment]
#26 Probably the same Issue

**Comment by Fourmisain** [comment]
If you got the build from Modrinth, please get the last [buildfix](https://modrinth.com/mod/tax-free-levels/version/1.3.10+buildfix) release.
Apparently my Modrinth build failed to execute a task before uploading.

**Comment by Fourmisain** [comment]
This crash should be the same as #26 as I don't think I touched anything related to Waystones.
The original build issue that caused #26 has been fixed now.
Let me know if there's still any issues even with the buildfix version.
