### ISSUE TITLE
Crash on startup client - 1.20.1 Mod version 1.3.10

### ISSUE THREAD

**Issue by VillainVibe** [Fourmisain/TaxFreeLevels#26]
Client fails to load on startup 

[pastbin crashlog.txt](https://github.com/Fourmisain/TaxFreeLevels/files/15049822/pastbin.crashlog.txt)

**Comment by Fourmisain** [comment]
Oh, that's weird!
It looks like the Modrinth build is incorrect, the CurseForge build doesn't have this issue.
I uploaded a [fixed build](https://modrinth.com/mod/tax-free-levels/version/1.3.10+buildfix) until I figure out why that happened.

**Comment by Fourmisain** [comment]
Aha, not so weird afterall.
I only recently added the publish script and 1.3.10 was the first version released by it - I just assumed it would work.
This is now fixed (e32805a3bdbfb8b60bec84001c789ff74e1cf327) and should never happen again.

**Comment by VillainVibe** [comment]
Everything is in working order after updating now 
Thank you very much!  :)
