### ISSUE TITLE
Anvil and Table costs are not tax free.

### ISSUE THREAD

**Issue by SengeeSama** [Fourmisain/TaxFreeLevels#28]
On minecraft version 1.21.1
When I'm repairing or combining items/books the cost is just like vanilla minecraft.
For example, repairing an item for a cost of 2 levels when at level 30 gets you down to 28, which is not the xp value of lvl 0-2.
This is also true for the enchanting table. I got a 1 level cost enchant with level req 8 (which should cost the xp value of getting from level 7-8) cost me exactly 1 whole level from 24-23.

**Comment by Fourmisain** [comment]
This is indended, please read the mod description again.
It reduces the costs **above level 30**, so if you're level 35 and the cost is 2, you're paying the XP from 33 to 35.
Costs up to level 30 are (almost) untouched.

Older versions of the mod did the calculation from level 0 and I found this to absolutely destroy the balancing of the game.

**Comment by Fourmisain** [comment]
To further explain this, the main issue is the enchanting table. It has as a level requirement, which goes up to 30.
If you level 3 enchant an item in it, you pay at minimum the XP from level 27 to 30 in vanilla, which is 306 XP.
If the cost calculation would shift this to level 0, this would only cost a measly 27 XP, which is **10 times less** than it's supposed to be.

**Comment by Fourmisain** [comment]
Ah, sorry, you did say it should start at the level requirement. Nevermind my last comment then.

Still, I felt similar issues with the anvil, where small level costs were much too cheap due to the quadratic level scaling, e.g. only paying 7 XP for level 1 when a Zombie is giving 5 XP.
It was too finicky to balance because you never have level 1 when you pay 1 level in vanilla, hence I just made it only apply to level 30 and above, where it _really_ matters. Where it's basically quality of life once you got a mob farm going.

That all said, I might make this configurable in the future.

**Comment by SengeeSama** [comment]
I see your point, but that wasn't what came across in the mod description and I personally disagree with you saying it's unbalanced. Normal minecraft is beyond absurd, and having it the way I described is what I think is actually balanced. I've kind of solved it already myself by using 2 other mods, a level curve flattner for the enchant table and an anvil balancer mod that turns the costs from levels to the corresponding 0-[whateverlevel] in XP. And it also completely removes the insane cost increase of repairs and putting enchant after enchant on the same item.
I don't expect anything from you as I'm satisfied with my personal solution, I just wanted to give you my opinion on the matter :)

**Comment by Fourmisain** [comment]
1.4 will probably be more to your liking.
Everything is now fully "tax free" by default, configurable level base of 0, down from 30, respecting the level requirement of the Enchanting Table, no "Too Expensive!" by default and whatnot!
