### ISSUE TITLE
Tax Free Levels 1.4.0 Doesn't Work

### ISSUE THREAD

**Issue by LordOfTheWeebs** [Fourmisain/TaxFreeLevels#30]
I tried to update Tax Free Levels to 1.4.0, and it causes a crash. I thought it might have been a conflict with one of the mods in my pack, so I created a separate instance with only it and its dependencies of Fabric API (0.105.0+1.21.1) and Cloth Config (15.0.140), using Fabric 0.16.7 on Minecraft 1.21.1, and it continued to crash.

[latest.log](https://github.com/user-attachments/files/17370454/latest.log)

**Comment by itsJaCaL** [comment]
Same

**Comment by Fourmisain** [comment]
> could not find any targets matching 'applyEnchantmentCosts'

Oh no, looks like the build failed and used the wrong refmap, not sure what's up with that, but should be an easy fix.

And Forge actually broke too, for a different reason that I don't understand at all right now. Didn't I test this...?
NeoForge works as expected at least.

Anyways, sorry for the hickup, 1.4.1 is up and running!

**Comment by Fourmisain** [comment]
This is so odd... after retesting, 1.4.0 Forge suddenly loads as expected.

Before I was getting `NoSuchMethod: io.github.fourmisain.taxfreelevels.forge.TaxFreeLevelsForge.<init>` which seems to imply Forge wanted to use the wrong mod constructor.

I can only assume there must be some bug with Forge - or maybe Architectury Loom, but oh well, 1.4.1 should be good for now.

**Comment by Fourmisain** [comment]
Ah, I think I finally figured out what the Forge issue was, I was accidentally running it with 1.21 (where it's broken), not 1.21.1 (where it was fine all along).

I'll just delete the new Forge version and restrict it to 1.21.1.
