### ISSUE TITLE
1.18 Mod Incompatibility (LevelZ possibly)

### ISSUE THREAD

**Issue by kaidejager** [Fourmisain/TaxFreeLevels#4]
Getting a crash with a beta version of LevelZ
[latest.log](https://github.com/Fourmisain/TaxFreeLevels/files/7655848/latest.log)

https://github.com/Globox1997/LevelZ/issues/60

**Comment by Fourmisain** [comment]
Ah, forgot this issue was still open. LevelZ is now fully compatible with Tax Free Levels.
