### ISSUE TITLE
Charm and Waystones compatibility

### ISSUE THREAD

**Issue by Darkmega18** [Fourmisain/TaxFreeLevels#6]
I currently have a modpack I'd be interested in taking your mod into. However I've noticed some things which don't have their xp tax flattened:

**Charm:** Grindstone disenchantment. Similar mechanic to the standalone mod you have cross compat with, so likely can be fixed in much the same way...? maybe? hopefully?

**Waystones:** Costs levels to transport between waystones. Tester says that they still tax you when transporting.

Would you be able to take a look at these, please?

**Comment by Fourmisain** [comment]
Quickly looked into it, looks like Charm compat is doable.
Do you mean [Fabric Waystones](https://www.curseforge.com/minecraft/mc-mods/fabric-waystones) or [Waystones (Fabric Edition)](https://www.curseforge.com/minecraft/mc-mods/waystones-fabric)?
Because Fabric Waystones can be configured to use a flat XP cost (by setting `cost_type` to `xp`), so it feels a pretty pointless to add compatibility to that.

**Comment by Fourmisain** [comment]
I put a prerelease with Charm compatibility [here](https://github.com/Fourmisain/TaxFreeLevels/releases/tag/1.3-1.16.5%2Bcharm).
Lemme know about Waystones so I can make a proper release later.

**Comment by Darkmega18** [comment]
> Quickly looked into it, looks like Charm compat is doable. Do you mean [Fabric Waystones](https://www.curseforge.com/minecraft/mc-mods/fabric-waystones) or [Waystones (Fabric Edition)](https://www.curseforge.com/minecraft/mc-mods/waystones-fabric)? Because Fabric Waystones can be configured to use a flat XP cost (by setting `cost_type` to `xp`), so it feels a pretty pointless to add compatibility to that.

oh, um. the forge version please, waystones which shows up in most popular first by blaytheninth: https://www.curseforge.com/minecraft/mc-mods/waystones . I'll have to check the configs for waystones to see if that exists currently. in which case, sorry about that.

I'll see about testing the charm compat tomorrow when I'm available again. Thank you. :)

**Comment by Darkmega18** [comment]
Just checked the configs for waystones, doesn't seem to have the option. it's based on levels that increase based on blocks traveled I believe.

**Comment by Fourmisain** [comment]
> oh, um. the forge version please

Dang it! :smile:
I expected Charm meant Fabric since Forge has the original Quark.

Forge compat will be an issue because Charm uses the ForgeGradle build system while I use Architectury and I have no idea if there's a way to compile one against the other. In the worst case I'd have to switch to ForgeGradle, which is a gruesome task (there's a reason I use Architectury).

This could take days or weeks, no ETA on that one.

**Comment by Darkmega18** [comment]
well thats a frick. D: I'm sorry, I shoulda specified my modloader also, forgetting you've got both going.

**Comment by Fourmisain** [comment]
I found a somewhat hacky workaround to get Charm going (by directly compiling against the Charm binaries).
Give it a try [here](https://github.com/Fourmisain/TaxFreeLevels/releases/tag/1.3.1-forge-1.16.5-charm).

Won't be as easy for Waystones I feel, still no ETA on that.

**Comment by Darkmega18** [comment]
roger-roger

**Comment by Fourmisain** [comment]
k, was able to basically do the same for Waystones too, here's the [prerelease](https://github.com/Fourmisain/TaxFreeLevels/releases/tag/1.3.1-forge-1.16.5-charm-waystones).

Technically that's it for this issue but I'll leave it open as a reminder for me to find a proper solution (and to add this for newer versions too).

**Comment by Darkmega18** [comment]
Thanks a lot. I'll give it a go!

**Comment by Darkmega18** [comment]
Will this pre-release be placed onto curseforge? it seems to be working. but if I'm to eventually update my pack I need it available on curseforge to be accepted I think.

**Comment by Fourmisain** [comment]
I can upload it as an alpha or beta, not quite sure how CurseForge modpacks deal with that though...?

**Comment by Darkmega18** [comment]
as long as it exists on curseforge I should be able to use it for my pack. 
just alphas don't show in the launcher unless downloaded manually and then it detects it and shows the version or you allow alphas in the settings and then manually install one from the version list.
Beta would be more accessible and stuff, and people could get it if they need it, or "stick to the release, for stability" as some do.

**Comment by Fourmisain** [comment]
Uploaded it as a beta just now, should soon be approved.

**Comment by INooBTooMuch** [comment]
Will this come to Forge for 1.18.2 (for the waystones) or are old(er) mc versions not supported?

**Comment by Fourmisain** [comment]
Ah, I never finished this, didn't I? Thanks for the reminder!

Looks like Charm is still stuck on 1.16, as is Lost Trinkets, so I forward-ported the Waystones compatibility to 1.17 - 1.19.
Get it while it's hot, on [Modrinth](https://modrinth.com/mod/tax-free-levels/version/1.3.4) or [CurseForge](https://www.curseforge.com/minecraft/mc-mods/tax-free-levels/files/4397239) of course.

**Comment by Fourmisain** [comment]
I guess this issue can now be closed.
Let me know if Charm gets ported to newer versions so I can update Tax Free Levels accordingly!
