### ISSUE TITLE
[Suggestion] Remove too expensive message on anvils

### ISSUE THREAD

**Issue by winsrp** [Fourmisain/TaxFreeLevels#8]
Can you make it so that we don't get that too expensive message on anvils?

**Comment by Fourmisain** [comment]
Quoting myself from the CurseForge page:

> This is (at least currently) not planned because there's a lot of mods that already do this, e.g. NoExpensive for Fabric, which is tested compatible - not sure about Forge but there has to be one too.

**edit**: I wouldn't really recommend NoExpensive e.g. due to their Mending+Infinity change.

> There's also Anvil Fix for 1.16, a 1.18 port called Anvil Fix Binchibubil and another mod called Forging Beyond for 1.17-1.18 which should all be compatible with Tax Free Levels.

For Forge 1.18, [Xp Is No Object](https://www.curseforge.com/minecraft/mc-mods/xpisnoobject) seems to be a good one that surely is compatible too.

**Comment by winsrp** [comment]
yeah, the problem with most of those other mods that do a similar thing, is that they are just normally updated for a very short time, so e.g. 1.19 comes around and now the mod and the feature is dead because it was never updated... 

So I prefer to stick with mods that have passed the test of time... test of versions... you know what I mean XD.

**Comment by Fourmisain** [comment]
Anvil Fix with 300k downloads did pass the test of time, I just saw it now has official 1.18 versions too.

The thing about adding the feature is that it needs to be configurable, which I usually do by adding Cloth Config as a dependency, but adding a huge dependency for a single setting isn't ideal to say the least.
I'd need to release at least 6 new version for Fabric and Forge 1.16-1.18 too, hence why I'm holding off until there's a more substantial reason.

That said, when 1.19 comes around, I might add it as a config file exclusive option (so it won't need Cloth Config).

**Comment by Fourmisain** [comment]
Actually, adding it as a setting would even require server -> client config synchronization...
Yeah, I'm definitely leaving that for the future. 😄

**Comment by winsrp** [comment]
well the guy from xp is no object said, it is only 10 lines of code, shouldn't be that complicated right? XD

**Comment by Fourmisain** [comment]
Yes, but I don't want to have the feature enabled by default (because it's not the focus of this mod) and that's what makes everything so complicated.

**Comment by winsrp** [comment]
ohhh, I see, ok, hopefully you can change your mind in the future!, tx!

**Comment by Fourmisain** [comment]
_Finally_ came around to it.
1.4 removes "Too Expensive!" by default, it's configurable and the server -> client sync is there.
